[package]
name = "nails"
version = "0.1.0"
authors = ["Stu Hood <stuhood@twitter.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
futures-cpupool = "0.1"
lazy_static = "0.2"
tokio-core = "0.1"
tokio-io = "0.1"
